while true; do
    clear
    echo -e "${BOLD}${CYAN}"
    echo "###################################################"
    echo "#   KIỂM TRA THÀNH VIÊN NHÓM TELEGRAM TRƯỚC KHI   #"
    echo "#         TIẾP TỤC CÀI ĐẶT RL-SWARM               #"
    echo "###################################################"
    echo -e "${NC}"
    echo -e "${YELLOW}"
        echo "===================================================="
        echo " BẠN CHƯA THAM GIA NHÓM TELEGRAM BẮT BUỘC!"
        echo ""
        echo " Vui lòng tham gia nhóm Telegram sau để tiếp tục:"
        echo ""
        echo -e "${BOLD}${CYAN}👉 $TELEGRAM_GROUP_LINK 👈${NC}${YELLOW}"
        echo ""
        echo " Sau khi tham gia, nhấn phím bất kỳ để kiểm tra lại!"
        echo "===================================================="
        echo -e "${NC}"
        read -n 1 -s -r -p ""
done
